Latest push
Signed-off-by: Hollow Man <hollowman@hollowman.ml>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -42,15 +42,6 @@ stages:
   - error
   - retry
 
-star:
-  stage: wait
-  script:
-    - 'curl --request POST
-      --header "PRIVATE-TOKEN: $GPATOKEN"
-      "https://gitlab.com/api/v4/projects/25111961/star"'
-  rules:
-    - if: $GPATOKEN != ""
-
 wait:
   stage: wait
   script:
@@ -58,12 +49,28 @@ wait:
   rules:
     - if: $DELAYS != ""
 
-run:
+star:
   stage: run
   script:
-    - python LZU-Auto-COVID-Health-Report.py >> information.txt
-    - cat information.txt
-    - python Notify-Result.py success $CI_JOB_URL
+    - 'curl --request POST
+      --header "PRIVATE-TOKEN: $GPATOKEN"
+      "https://gitlab.com/api/v4/projects/25111961/star"'
+  rules:
+    - if: $GPATOKEN != ""
+
+run:
+  stage: run
+  script: |
+    echo "---Auto COVID Health Report---"
+    if python /LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt;
+    then
+        echo "---Notify Success---"
+        python /Notify-Result.py success
+    else
+        echo "---Error logging and Notifying---"
+        python /Notify-Result.py failure && cat information.txt
+        exit 1
+    fi
 
 error:
   stage: error
@@ -76,7 +83,7 @@ retry:
   stage: retry
   script:
     - 'curl --request POST
-      --header "PRIVATE-TOKEN: $GPATOKEN"
+      --form token=$GPATOKEN"
       --form ref=main
       --form "variables[DELAYS]=30m"
       "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"'
