Latest push
Signed-off-by: Hollow Man <hollowman@hollowman.ml>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,11 +1,6 @@
-# Official language image. Look for the different tagged releases at:
-# https://hub.docker.com/r/library/python/tags/
 image: python:latest
 
-# Change pip's cache directory to be inside the project directory since we can
-# only cache local items.
 variables:
-  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
   CARDID: ""
   PASSWORD: ""
   SERVERCHANSCKEY: ""
@@ -17,24 +12,6 @@ variables:
   SUBSINFO: ""
   DELAYS: ""
   GPATOKEN: ""
-
-# Pip's cache doesn't store the python packages
-# https://pip.pypa.io/en/stable/reference/pip_install/#caching
-#
-# If you want to also cache the installed packages, you have to install
-# them in a virtualenv and cache it as well.
-cache:
-  paths:
-    - .cache/pip
-    - venv/
-
-before_script:
-  - python -V  # Print out python version for debugging
-  - pip install virtualenv
-  - virtualenv venv
-  - source venv/bin/activate
-  - python -m pip install --upgrade pip
-  - pip install -r requirements-run.txt
 
 stages:
   - wait
@@ -59,23 +36,23 @@ star:
 
 run:
   stage: run
-  script: |
-    echo "---Auto COVID Health Report---"
-    if python /LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt;
-    then
-        echo "---Notify Success---"
-        python /Notify-Result.py success
-    else
-        echo "---Error logging and Notifying---"
-        python /Notify-Result.py failure && cat information.txt
-        exit 1
-    fi
+  script:
+    - python -V  # Print out python version for debugging
+    - python -m pip install --upgrade pip
+    - pip install -r requirements-run.txt
+    - echo "---Auto COVID Health Report---";
+      if python LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt; then
+      echo "---Notify Success---";
+      python Notify-Result.py success; else
+      echo "---Error logging and Notifying---";
+      python Notify-Result.py failure && cat information.txt;
+      exit 1; fi
 
 retry:
   stage: retry
   script:
     - 'curl --request POST
-      --form token=$GPATOKEN"
+      --form token=$GPATOKEN
       --form ref=main
       --form "variables[DELAYS]=30m"
       "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"'
